# profiles/slurm/config.yaml
jobs: 100
default-resources:
  # Define default resources for rules unless overridden
  mem_mb: 32000
  time_min: 120

# Direct SLURM job submission with sbatch
cluster: "sbatch --parsable --cpus-per-task={threads} --mem={resources.mem_mb}M --time={resources.time_min} --job-name=sm.{rule}.{wildcards} --output={workdir}/logs/{rule}.{wildcards}.out --error={workdir}/logs/{rule}.{wildcards}.err --partition=day"

# Optional: specify status check script if needed
# cluster-status: "./slurm-status.py"

# Wait for output files for this many seconds
#latency-wait: 60

# Keep going if some jobs fail
keep-going: true

# Note: Partition, mail-user, mail-type are handled by defaults in slurm-submit.sh
# You could pass them here too if needed: --partition=day --mail-user=... etc.
# --------------------------------------------- 