# profiles/slurm/config.yaml
jobs: 100
default-resources:
  # Define default resources for rules unless overridden
  mem_mb: 32000
  time_min: 120

# The cluster submission command and cluster config file are now handled by the SLURM executor plugin
# based on convention (looking for cluster.yaml) and --executor slurm flag.

# Optional: specify status check script if needed
# cluster-status: "./slurm-status.py"

# Wait for output files for this many seconds
#latency-wait: 60

# Keep going if some jobs fail
keep-going: true

# Note: Partition, mail-user, mail-type are handled by defaults in slurm-submit.sh
# You could pass them here too if needed: --partition=day --mail-user=... etc.
# --------------------------------------------- 