# profiles/slurm/config.yaml
jobs: 100
default-resources:
  - mem_mb=32000 # Default 32GB RAM
  - time_min=120 # Default 2 hour runtime
cluster: >-
  sbatch
  --cpus-per-task={threads}
  --mem={resources.mem_mb}M
  --time=$(printf '%02d:%02d:00' $(({resources.time_min:-60}/60)) $(({resources.time_min:-60}%60)))
  --job-name=sm.{rule}.{wildcards}
  --output=logs/{rule}.{wildcards}.out
  --error=logs/{rule}.{wildcards}.err
  --partition=day
  --email=spenser.johnson@yale.edu
  --mail-type=END,FAIL
# --------------------------------------------- 